
email: wowthemesnet@gmail.com
timezone: UTC
baseurl: "/web"
permalink: "/:title/"

favicon: 'assets/images/favicon.svg'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: 

# Authors
authors:
  sal:
    name: JuntaAFA
    display_name: JuntaAFA
    avatar: 'assets/images/juntaAFA.png'
    email: afaescolatagamanent@gmail.com
    web: https://afaescolatagamanent.github.io/web
    description: "AFA Escola Tagamanent - Associació de Famílies d'Alumnes de l'Escola Tagamanent de Sant Pere de Vilamajor"
  john:
    name: Miquel Grau
    display_name: Miquel Grau
    avatar: 'assets/images/miquel.png'
    email: afaescolatagamanent@gmail.com
    web: https://afaescolatagamanent.github.io/web
    description: "AFA Escola Tagamanent - Associació de Famílies d'Alumnes de l'Escola Tagamanent de Sant Pere de Vilamajor"

# Social
social:
  instagram: https://www.instagram.com/afa_tagamanent/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
